config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about'
  resources :users, only: [:show, :index, :edit, :update]
  resources :books, except: [:new] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

    post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
    resources :relationships, only: :show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  attachment :profile_image, destroy: false

  # バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: { maximum: 20, minimum: 2 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  #フォロー機能
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  # ユーザーをフォローする
def follow(user_id)
  follower.create(followed_id: user_id)
end

# ユーザーのフォローを外す
def unfollow(user_id)
  follower.find_by(followed_id: user_id).destroy
end

# フォローしていればtrueを返す
def following?(user)
  following_user.include?(user)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    if @book_comment.save
      flash[:success] = "Comment was successfully created."
    end
    redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    book_comment = current_user.book_comments.find_by(id: params[:id], book_id: @book.id)
    book_comment.destroy
    redirect_to request.referer
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def show
    @user = User.find(params[:id])
    current_user.follow(params[:id])
    current_user.unfollow(params[:id])
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow(params[:id])
    redirect_to request.referer
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.unfollow(params[:id])
    redirect_to request.referer
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "successfully updated user!"
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>
		<% if @book.errors.any? %>
			<div id="error_explanation">
				<h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
				<ul>
					<% @book.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<%= render "books/newform", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<%= render 'layouts/error_messages', resource: @book %>
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<!-- いいね機能 -->
          <td>
            <% if book.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(book), method: :delete do %>
                <span class="glyphicon glyphicon-heart"><%= book.favorites.count%></span>
              <% end %>
            <% else %>
              <%= link_to book_favorites_path(book), method: :post do %>
                <span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></span>
              <% end %>
            <% end %>
          </td>
					<!-- いいね機能 -->
          <td>コメント数：<%= book.book_comments.count %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @book.user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book_new %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
							<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>
					<!-- いいね機能 -->
          <td>
            <% if @book.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(@book), method: :delete do %>
                <span class="glyphicon glyphicon-heart"><%= @book.favorites.count%></span>
              <% end %>
            <% else %>
              <%= link_to book_favorites_path(@book), method: :post do %>
                <span class="glyphicon glyphicon-heart-empty"><%= @book.favorites.count %></span>
              <% end %>
            <% end %>
          </td>
					<!-- いいね機能 -->
					<td>コメント数：<%= @book.book_comments.count %></td>

					<% if @book.user == current_user %>
						<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
						<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</table>
			<!-- コメント一覧 -->
			<table>
      <% @book_comments.each do |book_comment| %>
        <tr>
          <td class="show-comment">
            <%= link_to user_path(book_comment.user), class: "user_#{book_comment.user.id}" do %>
              <%= attachment_image_tag book_comment.user, :profile_image, fallback: "no_image.jpg", size: "50x50" %><br>
              <%= book_comment.user.name %>
            <% end %>
          </td>
          <td class="show-comment"><%= book_comment.comment %></td>
          <% if current_user == book_comment.user %>
            <td><%= link_to 'Destroy', book_book_comment_path(@book, book_comment), class: 'btn-sm btn-danger', method: :delete %></td>
          <% end %>
        </tr>
      <% end %>
    </table>

    <div class="comment-form">
      <%= form_for [@book, @book_comment] do |f| %>
        <%= f.text_area :comment, size: "90x5" %>
        <%= f.submit '送信', class: "btn-sm btn-primary" %>
      <% end %>
    </div>

    <!-- コメント一覧 -->
	</div>
</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to 'Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to 'Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to 'Books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to 'logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to 'Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to 'About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to 'sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to 'login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <div class="container">
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/relationships/follow.html.erb
<h2>Follow Users</h2>
<table class="table table-hover table-inverse">
	<thead>
		<tr>
		  <th>Image</th>
		  <th>Name</th>
		  <th colspan="3"></th>
		</tr>
    </thead>

	<tbody>
        <% @user.following_user.each do |user| %>
        <tr>
		  <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>

		  <td><%= "#{user.name}" %></td>

		  <td><%= "フォロー数: #{user.follower.count}" %></td>

		  <td><%= "フォロワー数: #{user.followed.count}" %></td>

		  <td><%= link_to "show", user_path(user) %></td>
		</tr>
        <% end %>
    </tbody>
</table>

app/views/relationships/show.html.erb
<h2>Follow Users</h2>
<table class="table table-hover table-inverse">
	<thead>
		<tr>
		  <th>Image</th>
		  <th>Name</th>
		  <th colspan="3"></th>
		</tr>
    </thead>

	<tbody>
        <% @user.following_user.each do |user| %>
        <tr>
		  <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>

		  <td><%= "#{user.name}" %></td>

		  <td><%= "フォロー数: #{user.follower.count}" %></td>

		  <td><%= "フォロワー数: #{user.followed.count}" %></td>

		  <td><%= link_to "show", user_path(user) %></td>
		</tr>
        <% end %>
    </tbody>
</table>

<h2>Follower Users</h2>
  <table class="table table-hover table-inverse">
	<thead>
		<tr>
		  <th>Image</th>
		  <th>Name</th>
	      <th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
        <% @user.follower_user.each do |user| %>
        <tr>
		  <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>

		  <td><%= "#{user.name}" %></td>

		  <td><%= "フォロー数: #{user.follower.count}" %></td>

		  <td><%= "フォロワー数: #{user.followed.count}" %></td>

		  <td><%= link_to "show", user_path(user) %></td>
		</tr>
        <% end %>
    </tbody>
</table>

app/views/relationships/unfollow.html.erb
<h2>Follower Users</h2>
  <table class="table table-hover table-inverse">
	<thead>
		<tr>
		  <th>Image</th>
		  <th>Name</th>
	      <th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
        <% @user.follower_user.each do |user| %>
        <tr>
		  <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>

		  <td><%= "#{user.name}" %></td>

		  <td><%= "フォロー数: #{user.follower.count}" %></td>

		  <td><%= "フォロワー数: #{user.followed.count}" %></td>

		  <td><%= link_to "show", user_path(user) %></td>
		</tr>
        <% end %>
    </tbody>
</table>

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>

        <tr>
        	<th>follows</th>
		    <th><%= link_to relationship_path(user), class: "user_#{user.id}" do %>
		    	<%= user.follower.count %>
		        <% end %>
		    </th>
	    </tr>

        <tr>
        	<th>followers</th>
	        <th>
	        	<%= link_to relationship_path(user), class: "user_#{user.id}" do %>
	        	<%= user.followed.count %>
	        	<% end %>
	        </th>
	    </tr>
</table>

<div class="row">
	<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

<br>

<div class="row">
    <% unless current_user == user %>
    <% if current_user.following?(user) %>
    <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST, class: 'btn btn-primary btn-block' %>
    <% else %>
    <%= link_to 'フォローする', follow_path(user.id), method: :POST, class: 'btn btn-success btn-block' %>
    <% end %>
    <% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<%= render 'layouts/error_messages', resource: @user %>

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>
	<div class="col-xs-9">
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name%></td>


                    <!--フォロー機能-->

                    <td><%= "フォロー数: #{user.follower.count}" %></td>

                    <td><%= "フォロワー数: #{user.followed.count}" %></td>
                    <td>
                      <% unless current_user == user %>
                      <% if current_user.following?(user) %>
                      <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
                      <% else %>
                      <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
                      <% end %>
                      <% end %>
                    </td>
                    <!--フォロー機能-->

                    <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>


				</tr>
				<% end %>
			</tbody>
		</table>
		<!--users一覧 -->
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--同コントローラーのviewで表示ならusersは省略可 -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>
	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>